<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Company>Aether Control</Company>
    <Product>Aether Control</Product>
    <Copyright>Copyright © Aether Control</Copyright>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Deterministic>true</Deterministic>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
</Project>
